### ISSUE TITLE
reproduce data processing

### ISSUE THREAD

**Issue by koenvandenberge** [RGLab/MASTdata#2]
Hi,

Could you please upload the files you used for the data processing of the two datasets?
Many other methods for sequencing analysis use count tables and we cannot reproduce these tables based on the singleCell Assay objects provided in the data package.

Thank you in advance,
Koen

**Comment by gfinak** [comment]
What files are you looking for exactly?
Fastq files are in the read sequence archive. The reference link is in the
paper.

Greg Finak

**Comment by koenvandenberge** [comment]
Dear Greg,

Thank you for the swift reply.
I am rather looking for the raw count table of the gene by sample matrix.

Koen

**Comment by gfinak** [comment]
Okay, thanks for the clarification. I was had thought those were in the package, let me look into it.

**Comment by gfinak** [comment]
Hi, Koen
The counts can be retrieved from the "counts" layer of the mait data single cell assay object. They are fractional, because they are "expected counts" from RSEM. We do not have integral counts since RSEM does not provide them. You could round to input the data into other methods, or realign from the fastq files and quantitate using a method that provides integral raw counts.
For the other data set, you should contact the Shalek lab directly to get the counts as they provided us only with tpm values.  
Best
Greg
