### ISSUE TITLE
Error when calling data

### ISSUE THREAD

**Issue by jhsiao999** [RGLab/MASTdata#3]
Hello,

I am writing to let you know that `data(MASTDataPacakge)` returned the following error:

```
Error in nrow(x@elementMetadata) : 
  no slot of name "elementMetadata" for this object of class "SingleCellAssay"
```

Any help would be greatly appreciate!

Joyce

**Comment by gfinak** [comment]
Thanks Joyce.
I think the MASTDataPackage  is compatible with the MASTclassic branch on
the RGLab GitHub (versions <0.99 of MAST). A lot has changed since then in
the package that is now on BioConductor, including how we store the
underlying data (thus the error).

If you are looking to reproduce analysis from the paper, you should use the
MASTClassic branch of the code.

If you are looking to analyze that data using the existing version, then
there is an API call: convertMASTClassicToSingleCellAssay() that will do
this.
Let me now if you have any other questions or if I can help in any way.
Best
Greg

**Comment by jhsiao999** [comment]
Hi Greg,

Thanks for the prompt reply. The API call worked perfectly!

Joyce
